/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author ah625
 */
public class SignInUI extends javax.swing.JFrame {

    /**
     * Creates new form SignInUI
     */
    public SignInUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        SubTitle1 = new javax.swing.JLabel();
        UsernameFeild = new javax.swing.JTextField();
        SubTitle2 = new javax.swing.JLabel();
        PasswordFeild = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        SignUpButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Title.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Sign In");
        getContentPane().add(Title);
        Title.setBounds(210, 10, 130, 47);

        SubTitle1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        SubTitle1.setText("Username");
        SubTitle1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(SubTitle1);
        SubTitle1.setBounds(60, 60, 90, 24);

        UsernameFeild.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        UsernameFeild.setText("Enter Your Username");
        UsernameFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFeildActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameFeild);
        UsernameFeild.setBounds(60, 90, 430, 50);

        SubTitle2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        SubTitle2.setText("Password");
        getContentPane().add(SubTitle2);
        SubTitle2.setBounds(60, 150, 90, 24);

        PasswordFeild.setText("jPasswordField1");
        getContentPane().add(PasswordFeild);
        PasswordFeild.setBounds(60, 180, 430, 50);

        LoginButton.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton);
        LoginButton.setBounds(205, 250, 140, 40);

        SignUpButton.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        SignUpButton.setText("S̲i̲gn̲ ̲U̲p");
        SignUpButton.setBorderPainted(false);
        SignUpButton.setContentAreaFilled(false);
        SignUpButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SignUpButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        SignUpButton.setIconTextGap(0);
        SignUpButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SignUpButton);
        SignUpButton.setBounds(200, 290, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void UsernameFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFeildActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PasswordFeild;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLabel SubTitle1;
    private javax.swing.JLabel SubTitle2;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField UsernameFeild;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
