package MainApplication.UI;

import MainApplication.Admin;
import MainApplication.Authentication;
import MainApplication.Route;
import MainApplication.UI.AdminUI;
import MainApplication.UI.MainFrame;

import java.awt.event.ActionEvent;

public class GenerateReportUI extends MainFrame {

    final Authentication auth;
    public GenerateReportUI(Authentication auth) {
        this.auth = auth;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        OField = new javax.swing.JTextField();
        DField = new javax.swing.JTextField();
        SubmitBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TotalBookingLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TotalFareLabel = new javax.swing.JLabel();
        GoBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Generate Report");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Origin Location");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Destination Location:");

        OField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        DField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        SubmitBtn.setText("Generate");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Total Fare:");

        TotalBookingLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TotalBookingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalBookingLabel.setText("0");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Total Number of Bookings:");

        TotalFareLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TotalFareLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalFareLabel.setText("0");
        TotalFareLabel.setToolTipText("");

        GoBack.setText("Go Back");
        GoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(OField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(DField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel6))
                                                .addGap(91, 91, 91)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(TotalBookingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(TotalFareLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(68, 68, 68)
                                                                .addComponent(jLabel1))
                                                        .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(GoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addComponent(GoBack)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(OField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3))
                                        .addComponent(SubmitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(24, 24, 24)
                                .addComponent(DField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TotalFareLabel)
                                        .addComponent(jLabel4))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TotalBookingLabel)
                                        .addComponent(jLabel6))
                                .addContainerGap(176, Short.MAX_VALUE))
        );

        this.setVisible(true);
    }

    private void SubmitBtnActionPerformed(ActionEvent evt) {
        Admin user = (Admin) auth.getCurrentAccount();

        if (OField.getText().isEmpty() || DField.getText().isEmpty()) {
            this.showNotification("Invalid inputs", "Fields empty", true);
            return;
        }

        Route route = new Route(OField.getText(), DField.getText());
        double fare = user.getTotalRouteFare(route);
        int bookings = user.getTotalBookingCount(route);

        TotalFareLabel.setText(fare + "$");
        TotalBookingLabel.setText("" + bookings);
    }
    private void GoBackActionPerformed(java.awt.event.ActionEvent evt) {
        new AdminUI(auth);
        this.dispose();
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField DField;
    private javax.swing.JButton GoBack;
    private javax.swing.JTextField OField;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel TotalBookingLabel;
    private javax.swing.JLabel TotalFareLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration
}
