
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lionkiller
 */
public class AddFlightUI extends javax.swing.JFrame {

    /**
     * Creates new form AddFlightUI
     */
    public AddFlightUI() {
        initComponents();
    }

    public radioButtonKeylistener(){
        setTitle("Key listener");
        setSize(300, 150);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Flight_ID_textbox = new javax.swing.JTextField();
        radio = new javax.swing.ButtonGroup();
        Flight_title = new javax.swing.JLabel();
        Flight_NUM = new javax.swing.JLabel();
        Route = new javax.swing.JLabel();
        Enter_NUM = new javax.swing.JTextField();
        Route_name = new javax.swing.JTextField();
        Route1 = new javax.swing.JLabel();
        Economy_radio = new javax.swing.JRadioButton();
        First_class = new javax.swing.JRadioButton();
        Seats = new javax.swing.JLabel();
        Arrival_Date = new javax.swing.JFormattedTextField();
        Business_class = new javax.swing.JRadioButton();
        ADD = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Seat = new javax.swing.JTable();
        Departure = new javax.swing.JLabel();
        Departure_Date = new javax.swing.JFormattedTextField();

        Flight_ID_textbox.setText("jTextField1");
        Flight_ID_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Flight_ID_textboxActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        Flight_title.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        Flight_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Flight_title.setText("Add Flight");
        getContentPane().add(Flight_title);
        Flight_title.setBounds(0, 0, 620, 95);

        Flight_NUM.setText("     Flight Number: ");
        getContentPane().add(Flight_NUM);
        Flight_NUM.setBounds(50, 90, 120, 60);

        Route.setText("    Route:");
        getContentPane().add(Route);
        Route.setBounds(60, 160, 90, 40);

        Enter_NUM.setText("   Enter flight number");
        Enter_NUM.setToolTipText("");
        Enter_NUM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Enter_NUMFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Enter_NUMFocusLost(evt);
            }
        });
        Enter_NUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enter_NUMActionPerformed(evt);
            }
        });
        getContentPane().add(Enter_NUM);
        Enter_NUM.setBounds(270, 100, 230, 40);

        Route_name.setText("   Enter your Route");
        Route_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Route_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Route_nameFocusLost(evt);
            }
        });
        Route_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Route_nameActionPerformed(evt);
            }
        });
        getContentPane().add(Route_name);
        Route_name.setBounds(270, 160, 230, 42);

        Route1.setText("    Arrival:");
        getContentPane().add(Route1);
        Route1.setBounds(30, 370, 80, 40);

        radio.add(Economy_radio);
        Economy_radio.setText("Economy");
        Economy_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Economy_radioActionPerformed(evt);
            }
        });
        getContentPane().add(Economy_radio);
        Economy_radio.setBounds(70, 260, 100, 25);

        radio.add(First_class);
        First_class.setText("First class");
        First_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                First_classActionPerformed(evt);
            }
        });
        getContentPane().add(First_class);
        First_class.setBounds(70, 290, 100, 25);

        Seats.setText("    Seat type:");
        getContentPane().add(Seats);
        Seats.setBounds(60, 220, 120, 40);

        Arrival_Date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd/yyyy"))));
        Arrival_Date.setText("MM/DD/YYYY");
        Arrival_Date.setToolTipText("");
        Arrival_Date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Arrival_DateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Arrival_DateFocusLost(evt);
            }
        });
        Arrival_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arrival_DateActionPerformed(evt);
            }
        });
        getContentPane().add(Arrival_Date);
        Arrival_Date.setBounds(120, 380, 164, 22);

        radio.add(Business_class);
        Business_class.setText("Business class");
        Business_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Business_classActionPerformed(evt);
            }
        });
        getContentPane().add(Business_class);
        Business_class.setBounds(70, 320, 120, 25);

        ADD.setText("Add Flight");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        getContentPane().add(ADD);
        ADD.setBounds(240, 470, 120, 40);

        Seat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", " 1 ", " 1 ", " 1", " 1", " 1", "1 ", "1"},
                {"2 ", "2", "2", "2", "2", "2", "2", "2"},
                {"3", "3", "3", "3", "3", "3", "3", "3"},
                {"4", "4", "4", "4", "4", "4", "4", "4"}
            },
            new String [] {
                "A", "B", "C", "D", "F", "G", "H", "I"
            }
        ));
        Seat.setColumnSelectionAllowed(true);
        Seat.getTableHeader().setReorderingAllowed(false);
        Seat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SeatKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(Seat);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(230, 260, 380, 90);

        Departure.setText("    Departure:");
        getContentPane().add(Departure);
        Departure.setBounds(320, 370, 80, 40);

        Departure_Date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd/yyyy"))));
        Departure_Date.setText("MM/DD/YYYY");
        Departure_Date.setToolTipText("");
        Departure_Date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Departure_DateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Departure_DateFocusLost(evt);
            }
        });
        Departure_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Departure_DateActionPerformed(evt);
            }
        });
        getContentPane().add(Departure_Date);
        Departure_Date.setBounds(410, 380, 164, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Flight_ID_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Flight_ID_textboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Flight_ID_textboxActionPerformed

    private void Enter_NUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enter_NUMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Enter_NUMActionPerformed

    private void Economy_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Economy_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Economy_radioActionPerformed

    private void First_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_First_classActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_First_classActionPerformed

    private void Route_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Route_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Route_nameActionPerformed

    private void Arrival_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arrival_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Arrival_DateActionPerformed

    private void Route_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Route_nameFocusGained
        // TODO add your handling code here:
        Route_name.setText("");
    }//GEN-LAST:event_Route_nameFocusGained

    private void Enter_NUMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Enter_NUMFocusGained
        // TODO add your handling code here:
        Enter_NUM.setText("");
    }//GEN-LAST:event_Enter_NUMFocusGained

    private void Enter_NUMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Enter_NUMFocusLost
        // TODO add your handling code here:
        Enter_NUM.setText("    Enter flight number");
    }//GEN-LAST:event_Enter_NUMFocusLost

    private void Route_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Route_nameFocusLost
        // TODO add your handling code here:
        Route_name.setText("   Enter your Route");
                
    }//GEN-LAST:event_Route_nameFocusLost

    private void Arrival_DateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Arrival_DateFocusGained
        // TODO add your handling code here:
       Arrival_Date.setText("");
    }//GEN-LAST:event_Arrival_DateFocusGained

    private void Arrival_DateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Arrival_DateFocusLost
        // TODO add your handling code here:
        Arrival_Date.setText("MM/DD/YYYY");
    }//GEN-LAST:event_Arrival_DateFocusLost

    private void Business_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Business_classActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Business_classActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDActionPerformed

    private void SeatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SeatKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatKeyPressed

    private void Departure_DateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Departure_DateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Departure_DateFocusGained

    private void Departure_DateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Departure_DateFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Departure_DateFocusLost

    private void Departure_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Departure_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Departure_DateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddFlightUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddFlightUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddFlightUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) { 
//            java.util.logging.Logger.getLogger(AddFlightUI.class.getName()).log(java.ussging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFlightUI().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JFormattedTextField Arrival_Date;
    private javax.swing.JRadioButton Business_class;
    private javax.swing.JLabel Departure;
    private javax.swing.JFormattedTextField Departure_Date;
    private javax.swing.JRadioButton Economy_radio;
    private javax.swing.JTextField Enter_NUM;
    private javax.swing.JRadioButton First_class;
    private javax.swing.JTextField Flight_ID_textbox;
    private javax.swing.JLabel Flight_NUM;
    private javax.swing.JLabel Flight_title;
    private javax.swing.JLabel Route;
    private javax.swing.JLabel Route1;
    private javax.swing.JTextField Route_name;
    private javax.swing.JTable Seat;
    private javax.swing.JLabel Seats;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.ButtonGroup radio;
    // End of variables declaration//GEN-END:variables
}
